services:
  db:
    image: postgres:15
    env_file:
      - back/.env
    environment:
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  back:
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    volumes:
      - ./back:/app
    ports:
      - "3001:3000"
    env_file:
      - back/.env
    depends_on:
      - db

  front:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    volumes:
      - ./front:/app
    ports:
      - "3000:3000"
    env_file:
      - back/.env
    depends_on:
      - back
    command: npm run dev

volumes:
  db_data:
